### ISSUE TITLE
BUG - JUnit report only generated when ALL tests pass - Reasoner Violations are reported as Exceptions with StackTrace

### ISSUE THREAD

**Issue by JWT007** [opencaesar/owl-tools#10]
## Description
Currently when a reasoner violation occurs while running the owl-reason (or owl-reason-gradle), an exception is thrown and a stack trace is generated.

Only when all tests pass (no violations) is a JUnit report generated... which is pretty useless when it is always a 100% pass report.

From an article on Baeldung:
_"Both failure and error in JUnit tests indicate an undesired situation, but their semantics are different. Failures notify of an invalid test result, errors indicate an unexpected test execution."_

## Expected Behavior
The expected behavior is that any reasoner violations are reported in the context of a failed JUnit test.  The reasoner explanation and stacktrace should be provided as details within the failed unit test.

In addition, the reasoner currently exits on the first reasoner violation by throwing the exception.  I would expect that all violations are collected and reported in the JUnit report.

Here is an example of a JUnit testsuite with one failed test and one passed test.  

![image](https://user-images.githubusercontent.com/28890586/89584448-61e11600-d83c-11ea-9348-c0a784692963.png)

**Comment by melaasar** [comment]
When a reasoning problem is detected, an exception is thrown but ALSO the junit (xml) result file is written to give you more details. Did you check the file in this case? I will modify it to mention that you can look at the result file for details explicitly in the exception message.

As a side, can you elaborate on the use case that led to the exception reported in the result file above? Or can you provide a reproducible use case? This does not seem like a reasoning problem, does it?

**Comment by melaasar** [comment]
I modified the error message to say "check the error log at [Path] for more details". Please feel free to reopen if more needs to be done, and provide more details.
