### ISSUE TITLE
owlQuery returns success status from exception

### ISSUE THREAD

**Issue by dwagmuse** [opencaesar/owl-tools#22]
## Description
If a query fails due to an exception thrown by the actual execution the task returns a default success status to gradle making gradle think it succeeded

## Steps to Reproduce
- [ ] Define an owlQuery task with a garbage SPARQL query
- [ ] execute it (note error message in log)
- [ ] try to run gradle again and it will not execute the failed query unless you use --rerun-tasks option

## Expected Behavior
* gradle session should not indicate a successful build status in this case
* task should continue to execute on subsequent runs until it does actually succeed
* 
## Relevant screenshots
If applicable, add screenshots to help illustrate the issue.

**Comment by dwagmuse** [comment]
I think the problem in owlQuery is that the exception handler for execution at line 158 https://github.com/opencaesar/owl-tools/blob/master/owl-query/src/main/java/io/opencaesar/owl/query/OwlQueryApp.java only prints a stack trace and then falls through to the default exit which will return a successful status.  It should signal a failed return status at that point.

**Comment by dwagmuse** [comment]
I’m less familiar with how scala does this but the render task appears to have exactly the same problem (in analysis tools): it collects and emits the error messages but it always exits with a default status.

It's also easy to see how a mistake like this could be made as the gradle documentation explaining how to write tasks fails to even mention that there IS a FAILED return status:

https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_outcomes

(there is, https://docs.gradle.org/current/javadoc/org/gradle/testkit/runner/TaskOutcome.html#FAILED)

But the documentation says absolutely NOTHING about error handling.

**Comment by dwagmuse** [comment]
Actually, now that I look at the code I see a lot more cases where exceptions are being suppressed. The code is suppressing just about every possible error and will need a more significant restructuring.

**Comment by melaasar** [comment]
Addressed as in v0.9.6
