### ISSUE TITLE
OwlReasonTask breaks due to commit 3cefaf0

### ISSUE THREAD

**Issue by mprather** [opencaesar/owl-tools#35]
## Description
Commit 3cefaf0 introduces a breaking change.  Previously working gradle tasks now fail with 

```
> Parameter -r should be a valid XML path
```

## Steps to Reproduce
Prior to 3cefaf0, it was possible to run a reasoning task in a clean folder (i.e. no pre-existing build folder).
With the latest change, a reasoning task cannot complete.

## Expected Behavior
No break in a clean setup, the task should be able to complete.

**Comment by melaasar** [comment]
Yes, this regression got introduced yesterday in 1.0.7. I fixed it and published a 1.0.8 to fix the regression.
