### ISSUE TITLE
Scheme with HTTPS break OwlReasonTask

### ISSUE THREAD

**Issue by mprather** [opencaesar/owl-tools#39]
## Description
Vocabulary bundles that use https for the scheme will break OwlReasonTask.

## Steps to Reproduce
In the vocabulary bundle file, define a namespace that uses http`s` as the scheme. For example...

```
vocabulary bundle <https://company/ontology/bundle#> as vb {
  // rest omitted for clarity
} 
```

Attempting to run the reasoner will fail. 

```
java.lang.NullPointerException

FAILURE: Build failed with an exception.
```

If the scheme is changed to a non-secure form (http), the reasoner will be able to process the bundle.

## Expected Behavior
No failure when a standard https scheme is used.

**Comment by melaasar** [comment]
This was a bug in OWL-Adapter and got fixed (as of 1.4.1) in https://github.com/opencaesar/owl-adapter/commit/6ab6d28de3e7b6f4e33f39f642fa0c7c8a07e2fb.
