### ISSUE TITLE
Documentation - build needs java 11 

### ISSUE THREAD

**Issue by xdobry** [opencaesar/owl-tools#7]
## Description
Despite of README.md file the build requires the jdk11 because of some build.gradle files.

## Steps to Reproduce
install and configure java 8
call gradlew build

Error

> Task :owl-reason:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':owl-reason:compileJava'.
> Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.

## Expected Behavior
The build works

## Additional Context
With openjdk 11 the build runs without errors

## Relevant screenshots
If applicable, add screenshots to help illustrate the issue.

**Comment by melaasar** [comment]
Updated the README to require JDK 11
